package runtime

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"shinya.click/cvm/bytecode"
	"shinya.click/cvm/codegen"
	"shinya.click/cvm/parser"
	"shinya.click/cvm/preprocessor"
	"shinya.click/cvm/sema"
)

func TestGCCExecutionGapReportIsCurrent(t *testing.T) {
	reportPath := filepath.Join("testdata", "gcc-exec", "gap-report.md")
	want := generateGCCExecGapReport(t)
	if os.Getenv("CVM_UPDATE_GCC_EXEC_GAP_REPORT") == "1" {
		if err := os.WriteFile(reportPath, []byte(want), 0644); err != nil {
			t.Fatalf("write GCC execution gap report: %v", err)
		}
		return
	}
	got, err := os.ReadFile(reportPath)
	if err != nil {
		t.Fatalf("read GCC execution gap report: %v", err)
	}
	if string(got) != want {
		t.Fatalf("%s is stale; regenerate it with CVM_UPDATE_GCC_EXEC_GAP_REPORT=1 go test ./runtime -run TestGCCExecutionGapReportIsCurrent -count=1", reportPath)
	}
}

type gccExecProbeResult struct {
	path  string
	stage string
	exit  int
	err   string
}

func generateGCCExecGapReport(t *testing.T) string {
	t.Helper()
	expectedExits := loadGCCExecManifestExits(t)
	results := probeGCCRunFixtures(t, expectedExits)
	counts := map[string]int{}
	for _, result := range results {
		counts[result.stage]++
	}

	var b strings.Builder
	b.WriteString("# GCC Runtime Execution Gap Report\n\n")
	b.WriteString("Generated by `go test ./runtime -run TestGCCExecutionGapReportIsCurrent -count=1`.\n")
	b.WriteString("Refresh with `CVM_UPDATE_GCC_EXEC_GAP_REPORT=1 go test ./runtime -run TestGCCExecutionGapReportIsCurrent -count=1`.\n\n")
	b.WriteString("Scope: GCC accept fixtures under `sema/testdata/gcc-*` whose source contains `{ dg-do run` or `{ dg-require-effective-target c99_runtime`.\n\n")

	b.WriteString("## Summary\n\n")
	b.WriteString("| stage | count |\n")
	b.WriteString("| --- | ---: |\n")
	for _, stage := range gccExecProbeStages() {
		b.WriteString(fmt.Sprintf("| %s | %d |\n", stage, counts[stage]))
	}
	b.WriteString(fmt.Sprintf("| total | %d |\n\n", len(results)))

	b.WriteString("## Manifest Candidates\n\n")
	candidates := filterGCCExecProbeResults(results, "ok")
	if len(candidates) == 0 {
		b.WriteString("No candidates currently run to completion.\n\n")
	} else {
		b.WriteString("| path | observed exit |\n")
		b.WriteString("| --- | ---: |\n")
		for _, result := range candidates {
			b.WriteString(fmt.Sprintf("| `%s` | %d |\n", result.path, result.exit))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Failures By Stage\n\n")
	for _, stage := range gccExecProbeFailureStages() {
		stageResults := filterGCCExecProbeResults(results, stage)
		if len(stageResults) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("### %s\n\n", stage))
		b.WriteString("| path | error |\n")
		b.WriteString("| --- | --- |\n")
		for _, result := range stageResults {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", result.path, markdownTableCode(result.err)))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Next Blockers\n\n")
	blockers := topGCCExecProbeBlockers(counts)
	if len(blockers) == 0 {
		b.WriteString("- No current blockers.\n")
	}
	for _, blocker := range blockers {
		b.WriteString(fmt.Sprintf("- `%s`: %d fixtures\n", blocker.stage, blocker.count))
	}
	return b.String()
}

func loadGCCExecManifestExits(t *testing.T) map[string]int {
	t.Helper()
	content, err := os.ReadFile(filepath.Join("testdata", "gcc-exec", "manifest.tsv"))
	if err != nil {
		t.Fatalf("read GCC execution manifest: %v", err)
	}
	cases := parseGCCExecManifest(t, string(content))
	exits := map[string]int{}
	for _, c := range cases {
		exits[c.path] = c.exitCode
	}
	return exits
}

func probeGCCRunFixtures(t *testing.T, expectedExits map[string]int) []gccExecProbeResult {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join("..", "sema", "testdata", "gcc-*", "accept", "*.c"))
	if err != nil {
		t.Fatalf("glob GCC accept fixtures: %v", err)
	}
	sort.Strings(paths)
	var results []gccExecProbeResult
	for _, fsPath := range paths {
		source, err := os.ReadFile(fsPath)
		if err != nil {
			t.Fatalf("read %s: %v", fsPath, err)
		}
		if !hasGCCRunDirective(string(source)) {
			continue
		}
		repoPath := filepath.ToSlash(strings.TrimPrefix(fsPath, ".."+string(filepath.Separator)))
		result := probeGCCExecFixture(repoPath, fsPath, string(source))
		if wantExit, ok := expectedExits[repoPath]; ok && result.stage == "ok" && result.exit != wantExit {
			result.stage = "exit-mismatch"
			result.err = fmt.Sprintf("observed exit %d, manifest wants %d", result.exit, wantExit)
		}
		results = append(results, result)
	}
	return results
}

func probeGCCExecFixture(repoPath, fsPath, source string) gccExecProbeResult {
	src := stripGCCDirectives(source)
	pp, err := preprocessor.PreprocessSource(fsPath, src, preprocessor.Options{})
	if err != nil {
		return failedGCCExecProbe(repoPath, "preprocess", err)
	}
	if parserTokenCount(pp.Tokens) == 0 {
		return gccExecProbeResult{path: repoPath, stage: "preprocess", err: "preprocess produced no parser tokens"}
	}
	candidates, err := parser.NewParser(pp.Tokens).Parse()
	if err != nil {
		return failedGCCExecProbe(repoPath, "parse", err)
	}
	prog, err := sema.AnalyzeWithOptions(candidates, gccSemaOptions(source))
	if err != nil {
		return failedGCCExecProbe(repoPath, "sema", err)
	}
	mod, err := codegen.Generate(prog)
	if err != nil {
		return failedGCCExecProbe(repoPath, "codegen", err)
	}
	var encoded bytes.Buffer
	if err := bytecode.EncodeModule(&encoded, mod); err != nil {
		return failedGCCExecProbe(repoPath, "encode-load", err)
	}
	p, err := Load(bytes.NewReader(encoded.Bytes()), LoadOptions{})
	if err != nil {
		return failedGCCExecProbe(repoPath, "encode-load", err)
	}
	st, err := Run(context.Background(), p, RunOptions{StepLimit: 100000})
	if err != nil {
		return failedGCCExecProbe(repoPath, "runtime", err)
	}
	return gccExecProbeResult{path: repoPath, stage: "ok", exit: st.Code}
}

func failedGCCExecProbe(path, stage string, err error) gccExecProbeResult {
	return gccExecProbeResult{path: path, stage: stage, err: summarizeGCCExecProbeError(err)}
}

func summarizeGCCExecProbeError(err error) string {
	msg := strings.TrimSpace(err.Error())
	if i := strings.IndexByte(msg, '\n'); i >= 0 {
		msg = msg[:i]
	}
	msg = strings.Join(strings.Fields(msg), " ")
	const maxLen = 180
	if len(msg) > maxLen {
		msg = msg[:maxLen-3] + "..."
	}
	return msg
}

func gccExecProbeStages() []string {
	return []string{"ok", "preprocess", "parse", "sema", "codegen", "encode-load", "runtime", "exit-mismatch"}
}

func gccExecProbeFailureStages() []string {
	return []string{"preprocess", "parse", "sema", "codegen", "encode-load", "runtime", "exit-mismatch"}
}

type gccExecProbeBlocker struct {
	stage string
	count int
}

func topGCCExecProbeBlockers(counts map[string]int) []gccExecProbeBlocker {
	var blockers []gccExecProbeBlocker
	for _, stage := range gccExecProbeFailureStages() {
		if counts[stage] > 0 {
			blockers = append(blockers, gccExecProbeBlocker{stage: stage, count: counts[stage]})
		}
	}
	sort.Slice(blockers, func(i, j int) bool {
		if blockers[i].count != blockers[j].count {
			return blockers[i].count > blockers[j].count
		}
		return blockers[i].stage < blockers[j].stage
	})
	const maxBlockers = 3
	if len(blockers) > maxBlockers {
		blockers = blockers[:maxBlockers]
	}
	return blockers
}

func filterGCCExecProbeResults(results []gccExecProbeResult, stage string) []gccExecProbeResult {
	var filtered []gccExecProbeResult
	for _, result := range results {
		if result.stage == stage {
			filtered = append(filtered, result)
		}
	}
	return filtered
}

func markdownTableCode(s string) string {
	s = strings.ReplaceAll(s, "`", "'")
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}
